title: ERGOSTATS
baseURL: https://www.facebook.com/ergostats
theme: Vno-Hugo
defaultContentLanguage: en-us
languages:
  en-us:
    languageName: English(United States)
    weight: 10
  zh-cn:
    languageName: 简体中文（中国大陆）
    paginate: 10
    paginatePath: page
    weight: 20
outputs:
  home:
    - HTML
    - RSS
menu:
  main:
    - identifier: projects
      name: Projects
      url: http://project.onevcat.com/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
taxonomies:
  tag: tags
params:
  author: onevcat
  blogButton:
    description: Visit blog
    title: Blog
  comment:
    disqus: vno-hugo
    duoshuo: ''
    gitalk:
      ID: ''
      owner: ''
      repo: ''
      secret: ''
  copyright:
    license: CC BY-NC-SA 4.0
    license_link: http://creativecommons.org/licenses/by-nc-sa/4.0/
  coverColor: red
  description: Centro Estadístico
  ga:
    ID: your_ga_id
    host: your_host
  social:
    github: ergostats
    facebook: ergostats
    linkedin: example
    mail: onev@onevcat.com
    twitter: onevcat
    weibo: onevcat
  subtitle: Investigación y Desarrollo
  welcomeMessage: Bienvenidos
permalinks:
  posts: /:year/:month/:title/
